[refactor]: stubs

diff --git a/polyglot/template/tool-template/_cmd b/polyglot/template/tool-template/_cmd
--- a/polyglot/template/tool-template/_cmd
+++ b/polyglot/template/tool-template/_cmd
@@ -5,11 +5,59 @@
 set -o nounset
 set -o pipefail
 
+DEFAULT_FILE="TODO.txt"
+
 # shellcheck disable=SC1091
 source "$POLY_SRC/lib/lib-util.bash"
 if [[ -e "$POLYGLOT_ROOT/.tasks/task-util.bash" ]]; then
+    # shellcheck disable=SC1091
     source "$POLYGLOT_ROOT/.tasks/task-util.bash"
 fi
 
+function print-help () {
+    case "${@: -1}" in
+        -h|--help) ;;
+        *) if [[ "$#" -gt 0 ]]; then
+               return
+           fi
+           ;;
+    esac
+    echo -e "
+usage: polyglot tool {tool} {cmd} [-h] [args...]
 
-echo "TODO: tool command."
+positional arguments:
+args      : arguments to pass to the tool
+
+options:
+-h, --help    : show this help message and exit
+
+"
+    exit "${PRINTED_HELP:-2}"
+}
+
+function handle-result () {
+    result="$1"
+    shift
+
+    case "$result" in
+        0) exit 0 ;;
+        1) fail "Command Failed" ;;
+        *) fail "Unknown result code: $result"
+    esac
+}
+
+function run-tool () {
+    echo "TODO"
+}
+
+function main () {
+    print-help "$@"
+    subhead "Parsing Args"
+    shift
+    _ARGS=("$@")
+    run-tool "$target" "$file" "${_ARGS[@]}"
+    handle-result "$?" "$target" "$file" "${_ARGS[@]}"
+    exit "$?"
+}
+
+main "$@"
