[refactor]:

diff --git a/polyglot/cmds/polyglot-add b/polyglot/cmds/polyglot-add
--- a/polyglot/cmds/polyglot-add
+++ b/polyglot/cmds/polyglot-add
@@ -36,40 +36,36 @@ options:
     exit "${PRINTED_HELP:-2}"
 }
 
-function verbose-result () {
-    if [[ "${VERBOSE:-0}" -eq 0 ]]; then
-       exit "$1"
-    fi
+function add-ws-member () {
+    local type="$1"
+    local name="$2"
+    local POLY_CTX="$POLY_CTX"
+    subhead "Adding $type: $name"
+    POLY_CTX=$(pushctx "$name")
 
-    if [[ "$1" -eq 0 ]]; then
-        echo "$target is loaded"
-    else
-        echo "$target is not loaded"
-    fi
-    exit "$1"
+    polyglot check "$type" "$name" && tdot "add" "Member already added" && return
+
+    (cookiecutter --no-input --output-dir "$POLYGLOT_ROOT/.tasks" "$type:$name" >/dev/null) || fail "Failed to create $type $name"
+
+    case "$type" in
+        tool|lang)
+            polyglot check "$type" "$name" init || return 0
+            polyglot "$type" "$name" init || fail "Failed to initialise $type $name"
+            ;;
+        task) ;;
+    esac
 }
 
 print-help "$@"
-
 type="$1"
 name="$2"
 
+[[ -d "$POLYGLOT_ROOT/.tasks" ]] || fail "Tasks directory does not exist"
+
 case "$type" in
-    util)
-        subhead "Creating lang-$name"
-        pushd "$POLYGLOT_ROOT/.tasks" || fail "Failed to go to tasks dir"
-        cookiecutter "$type:$name"
-        popd || fail "Failed to return from tasks dir"
-        ;;
-    tool|task|lang)
-        subhead "Creating $type-$name"
-        pushd "$POLYGLOT_ROOT/.tasks" || fail "Failed to go to tasks dir"
-        cookiecutter "$type:$name"
-        popd || fail "Failed to return from tasks dir"
-        ;;
-    *)
-        fail "Bad type. It should be one of [tool, task, lang]"
-        ;;
+    tool|lang|task) add-ws-member "$type" "$name" ;;
+    util)      add-ws-member "lang" "$name" ;;
+    *) fail "Bad type. It should be one of [tool, task, lang, util]" ;;
 esac
 
 
diff --git a/polyglot/cmds/polyglot-lang b/polyglot/cmds/polyglot-lang
--- a/polyglot/cmds/polyglot-lang
+++ b/polyglot/cmds/polyglot-lang
@@ -4,6 +4,7 @@
 set -o nounset
 set -o pipefail
 
+# shellcheck disable=SC1091
 source "$POLY_SRC/lib/lib-util.bash"
 
 function print-help () {
@@ -36,14 +37,12 @@ function list-subcmds () {
     local lang="$3"
     shift 3
     local count=0
-    if [[ -z "$lang" ]]; then
-        fail "No language Specified to list subcmds of"
-    elif [[ ! -d "$base/$prefix$lang" ]]; then
-        fail "Language could not be found: $lang"
-    fi
+    [[ -d "$lang" ]] || fail "No language Specified to list subcmds of"
+    [[ -d "$base/${prefix}-${lang}" ]] || fail "Language could not be found: $lang"
+
 
     echo -e "Active Subcommands for $lang: "
-    for subcmd in $(find "$base/$prefix$lang" -executable -a -type f | sort -V)
+    for subcmd in $(find "$base/${prefix}-${lang}" -executable -a -type f | sort -V)
     do
         bname=$( basename "$subcmd" )
         echo -e "-($count): ${bname}"
@@ -57,43 +56,25 @@ function run-subcmd () {
     # task is of the form lang-{sub} or lang-{sub}
     local base="$1"
     local prefix="$2"
-    local lang="${3:-}"
-    local target="${4:-}"
-    shift 3
+    local lang="$3"
+    local target="$4"
+    shift 4
     local count=0
-    if [[ -z "$target" ]]; then
-        fail "No Applicable language subcommand specified"
-    fi
-    debug "- Checking for subcommand ${prefix}$lang: $target"
-    if [[ ! -d "$base/$prefix$lang" ]]; then
-        fail "No Applicable lang Found: ${lang}"
-    fi
+    [[ -n "$target" ]] || fail "No Applicable language subcommand specified"
+    debug "- Checking for subcommand ${prefix}-$lang: $target"
+    [[ -d "$base/${prefix}-${lang}" ]] || fail "No Applicable lang Found: ${lang}"
 
-    local possible
-    readarray -d '' possible < <(find "$base/${prefix}${lang}" -name "${target}*" -a -executable -print0)
-    if [[ "${#possible[@]}" -lt 1 ]]; then
-        fail "No Possible Subcmds Found"
-    elif [[ "${#possible[@]}" -gt 1 ]]; then
-        fail "Too Many Possible Subcmds Found: ${#possible[@]}"
-    fi
-
-    sub="${possible[0]}"
-    if [[ -x "$sub" ]]; then
-        POLY_SRC="$POLY_SRC" "$sub" "$@"
-        echo "Result: $?"
-        return
-    else
-        echo "not executable"
-    fi
-    return "$NOTHING"
+    subcmd-run "$base/${prefix}-${lang}" "$target"
+    return "$?"
 }
 
 print-help "$@"
+
 DO_LIST=0
 TARGET_LANG=""
 SUBCMD=""
 LANG_ARGS=()
-while [[ $# -gt 0 ]]; do
+while [[ "$#" -gt 0 ]]; do
     case $1 in
         -l|--list)
             DO_LIST=1
@@ -112,8 +93,8 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-header "polyglot lang: $TARGET_LANG.$SUBCMD :(${#LANG_ARGS[@]}) ${LANG_ARGS[*]}"
-if [[ "$DO_LIST" = 1 ]]; then
-    list-subcmds "$POLYGLOT_ROOT/.tasks" "lang-" "$TARGET_LANG"
-fi
-run-subcmd "$POLYGLOT_ROOT/.tasks" "lang-" "$TARGET_LANG" "$SUBCMD" "${LANG_ARGS[@]}"
+subhead "Lang: $TARGET_LANG.$SUBCMD :(${#LANG_ARGS[@]}) ${LANG_ARGS[*]}"
+
+[[ "$DO_LIST" = 0 ]] || list-subcmds "$POLYGLOT_ROOT/.tasks" "lang" "$TARGET_LANG"
+
+run-subcmd "$POLYGLOT_ROOT/.tasks" "lang" "$TARGET_LANG" "$SUBCMD" "${LANG_ARGS[@]}"
diff --git a/polyglot/cmds/polyglot-new b/polyglot/cmds/polyglot-new
--- a/polyglot/cmds/polyglot-new
+++ b/polyglot/cmds/polyglot-new
@@ -14,9 +14,9 @@ function print-help () {
     case "${@: -1}" in
         -h|--help) ;;
         *) if [[ "$#" -gt 0 ]]; then
-               return
+              return
            fi
-           ;;
+              ;;
     esac
     echo -e "
 usage: polyglot new [-h]
@@ -34,20 +34,30 @@ options:
     exit "${PRINTED_HELP:-2}"
 }
 
-function verbose-result () {
-    if [[ "${VERBOSE:-0}" -eq 0 ]]; then
-       exit "$1"
-    fi
-
-    if [[ "$1" -eq 0 ]]; then
-        echo "$target is loaded"
-    else
-        echo "$target is not loaded"
-    fi
-    exit "$1"
-}
-
 print-help "$@"
 
-cookiecutter polyglot
-# TODO: iniitialise git
+proj_name="$1"
+
+if [[ -d "$PWD/${proj_name}" ]]; then
+    fail "Workspace already exists: ${proj_name}"
+fi
+
+header "Creating Workspace: $proj_name"
+POLY_CTX=$(pushctx "new")
+
+cookiecutter --no-input polyglot proj_name="$proj_name"
+[[ -d "$PWD/${proj_name}" ]] || fail "Failed to create project"
+pushd "${proj_name}" >/dev/null || fail "Failed to enter new project for initalisation"
+
+POLY_CTX=$(pushctx "workspace")
+pctx "Setting up workspace"
+
+tdot "git" "Initialising git"
+git init >/dev/null
+git add --all 2>/dev/null
+git commit -m "[initial]: workspace creation" 2>/dev/null >/dev/null
+
+direnv allow
+POLY_CTX="$POLY_CTX" direnv exec . polyglot task init     || fail "Failed to initialise"
+POLY_CTX="$POLY_CTX" direnv exec . polyglot task validate || fail "Failed to validate"
+popd >/dev/null || fail "Failed to enter new project"
diff --git a/polyglot/cmds/polyglot-tool b/polyglot/cmds/polyglot-tool
--- a/polyglot/cmds/polyglot-tool
+++ b/polyglot/cmds/polyglot-tool
@@ -38,14 +38,11 @@ function list-subcmds () {
     local tool="$3"
     shift 3
     local count=0
-    if [[ -z "$tool" ]]; then
-        fail "No Tool Specified to list subcmds of"
-    elif [[ ! -d "$base/$prefix$tool" ]]; then
-        fail "Tool could not be found: $tool"
-    fi
+    [[ -d "$tool" ]] || fail "No Tool Specified to list subcmds of"
+    [[ -d "$base/${prefix}-${tool}" ]] || fail "Tool could not be found: $tool"
 
     echo -e "Active Subcommands for $tool: "
-    for subcmd in $(find "$base/$prefix$tool" -executable -a -type f | sort -V)
+    for subcmd in $(find "$base/${prefix}-${tool}" -executable -a -type f | sort -V)
     do
         bname=$( basename "$subcmd" )
         echo -e "-($count): ${bname}"
@@ -54,42 +51,18 @@ function list-subcmds () {
     exit 0
 }
 
-function run-subcmd () {
-    # run-subcmd {basedir} {subcmd} {args}
+function run-tool-subcmd () {
+    # run-tool-subcmd {basedir} {subcmd} {args}
     # task is of the form lang-{sub} or tool-{sub}
     local base="$1"
     local prefix="$2"
-    local tool="${3:-}"
-    local target="${4:-}"
-    shift 3
-    local count=0
-    if [[ -z "$target" ]]; then
-        fail "No Applicable tool subcommand specified"
-    fi
-    debug "- Checking for subcommand ${prefix}$tool: $target"
-    if [[ ! -d "$base/$prefix$tool" ]]; then
-        fail "No Applicable Tool Found: ${tool}"
-    fi
+    local tool="$3"
+    local target="$4"
+    shift 4
+    [[ -d "$base/${prefix}-${tool}" ]] || fail "No Applicable Tool Found: ${tool}"
 
-    local possible
-    readarray -d '' possible < <(find "$base/${prefix}${tool}" -name "${target}*" -a -executable -print0)
-    if [[ "${#possible[@]}" -lt 0 ]]; then
-        fail "No Possible Subcmds Found"
-    elif [[ "${#possible[@]}" -gt 1 ]]; then
-        fail "Too Many Possible Subcmds Found: ${#possible[@]}"
-    elif [[ -z "${possible[0]:-}" ]]; then
-        fail "No possible subcmds found"
-    fi
-
-    sub="${possible[0]}"
-    if [[ -x "$sub" ]]; then
-        POLY_SRC="$POLY_SRC" "$sub" "$@"
-        echo "Result: $?"
-        return
-    else
-        echo "not executable"
-    fi
-    return "$NOTHING"
+    subcmd-run "$base/${prefix}-${tool}" "${target}"
+    return "$?"
 }
 
 print-help "$@"
@@ -116,8 +89,8 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-header "polyglot tool: $TOOL.$SUBCMD :(${#TOOL_ARGS[@]}) ${TOOL_ARGS[*]}"
-if [[ "$DO_LIST" = 1 ]]; then
-    list-subcmds "$POLYGLOT_ROOT/.tasks" "tool-" "$TOOL"
-fi
-run-subcmd "$POLYGLOT_ROOT/.tasks" "tool-" "$TOOL" "$SUBCMD" "${TOOL_ARGS[@]}"
+subhead "Tool: $TOOL.$SUBCMD :(${#TOOL_ARGS[@]}) ${TOOL_ARGS[*]}"
+
+[[ "$DO_LIST" = 0 ]] || list-subcmds "$POLYGLOT_ROOT/.tasks" "tool" "$TOOL"
+
+run-tool-subcmd "$POLYGLOT_ROOT/.tasks" "tool" "$TOOL" "$SUBCMD" "${TOOL_ARGS[@]}"
