[refactor]: task/tool/lang execution

diff --git a/polyglot/cmds/polyglot-lang b/polyglot/cmds/polyglot-lang
--- a/polyglot/cmds/polyglot-lang
+++ b/polyglot/cmds/polyglot-lang
@@ -5,9 +5,6 @@ set -o nounset
 set -o pipefail
 
 source "$POLY_SRC/lib/lib-util.bash"
-source "$POLY_SRC/lib/lib-hooks.bash"
-
-header "polyglot lang"
 
 function print-help () {
     case "${@: 1}" in
@@ -18,10 +15,105 @@ function print-help () {
            ;;
     esac
     echo -e "
-Run a registered language cmd.
+usage: polyglot lang [-h] [-l] [langname subcmd]
+
+Use a registered language's subcommand.
+
+positional arguments:
+langname
+subcmd
+
+options:
+-h, --help     :  show this help message and exit
+-l, --list     :  list the available subcmds of the language
 "
     exit 2
 }
 
+function list-subcmds () {
+    local base="$1"
+    local prefix="$2"
+    local lang="$3"
+    shift 3
+    local count=0
+    if [[ -z "$lang" ]]; then
+        fail "No language Specified to list subcmds of"
+    elif [[ ! -d "$base/$prefix$lang" ]]; then
+        fail "Language could not be found: $lang"
+    fi
+
+    echo -e "Active Subcommands for $lang: "
+    for subcmd in $(find "$base/$prefix$lang" -executable -a -type f | sort -V)
+    do
+        bname=$( basename "$subcmd" )
+        echo -e "-($count): ${bname}"
+        count=$(( 1 + count ))
+    done
+    exit 0
+}
+
+function run-subcmd () {
+    # run-subcmd {basedir} {subcmd} {args}
+    # task is of the form lang-{sub} or lang-{sub}
+    local base="$1"
+    local prefix="$2"
+    local lang="${3:-}"
+    local target="${4:-}"
+    shift 3
+    local count=0
+    if [[ -z "$target" ]]; then
+        fail "No Applicable language subcommand specified"
+    fi
+    debug "- Checking for subcommand ${prefix}$lang: $target"
+    if [[ ! -d "$base/$prefix$lang" ]]; then
+        fail "No Applicable lang Found: ${lang}"
+    fi
+
+    local possible
+    readarray -d '' possible < <(find "$base/${prefix}${lang}" -name "${target}*" -a -executable -print0)
+    if [[ "${#possible[@]}" -lt 1 ]]; then
+        fail "No Possible Subcmds Found"
+    elif [[ "${#possible[@]}" -gt 1 ]]; then
+        fail "Too Many Possible Subcmds Found: ${#possible[@]}"
+    fi
+
+    sub="${possible[0]}"
+    if [[ -x "$sub" ]]; then
+        POLY_SRC="$POLY_SRC" "$sub" "$@"
+        echo "Result: $?"
+        return
+    else
+        echo "not executable"
+    fi
+    return "$NOTHING"
+}
+
 print-help "$@"
-run-subcmd "$POLYGLOT_ROOT/.tasks" "lang-" "$@"
+DO_LIST=0
+TARGET_LANG=""
+SUBCMD=""
+LANG_ARGS=()
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -l|--list)
+            DO_LIST=1
+            ;;
+        *) # Positional
+            if [[ -z "$TARGET_LANG" ]]; then
+                TARGET_LANG="$1"
+            elif [[ -z "$SUBCMD" ]]; then
+                SUBCMD="$1"
+                shift
+                LANG_ARGS=("${@}")
+                break
+            fi
+            ;;
+    esac
+    shift
+done
+
+header "polyglot lang: $TARGET_LANG.$SUBCMD :(${#LANG_ARGS[@]}) ${LANG_ARGS[*]}"
+if [[ "$DO_LIST" = 1 ]]; then
+    list-subcmds "$POLYGLOT_ROOT/.tasks" "lang-" "$TARGET_LANG"
+fi
+run-subcmd "$POLYGLOT_ROOT/.tasks" "lang-" "$TARGET_LANG" "$SUBCMD" "${LANG_ARGS[@]}"
diff --git a/polyglot/cmds/polyglot-task b/polyglot/cmds/polyglot-task
--- a/polyglot/cmds/polyglot-task
+++ b/polyglot/cmds/polyglot-task
@@ -5,9 +5,6 @@ set -o nounset
 set -o pipefail
 
 source "$POLY_SRC/lib/lib-util.bash"
-source "$POLY_SRC/lib/lib-hooks.bash"
-
-header "polyglot task"
 
 function print-help () {
     case "${@: 1}" in
@@ -18,11 +15,152 @@ function print-help () {
            ;;
     esac
     echo -e "
-Call a specific registered task.
+usage: polyglot task [-h] [-l] [-hook=int] [target]
 
+Use a registered task.
+
+positional arguments:
+target
+
+options:
+-h, --help    : show this help message and exit
+-l, --list    : list the hooks of the target
+-d, --dry     : dry-run the hooks.
+--hook=int    : run just the nth hook of the target
 "
     exit 2
 }
 
+function run-task () {
+    # run-hooks {basedir} {task}
+    # task is of the form task-{}
+    local base="$1"
+    local prefix="$2"
+    local dry="$3"
+    local task="$4"
+    shift 4
+    local count=0
+    debug "- Checking for ${prefix/-/}: $task"
+    if [[ ! -d "$base/$prefix$task" ]]; then
+        return "$NOTHING"
+    fi
+    debug "- Running $task (dry=$dry)"
+
+    for hook in $(find "$base/$prefix$task" -executable -a -type f | sort -V)
+    do
+        hname=$( basename "$hook" )
+        if [[ "$dry" -gt 0 ]]; then
+            subhead "(dry) $hname ${*}"
+        else
+            (
+                POLY_SRC="$POLY_SRC" \
+                HOOK_NUM="$count" \
+                    "$hook" "$@"
+            )
+        fi
+        case "$?" in
+            0) # Normal hook completion
+                debug "- Hook Success"
+            ;;
+            1) # Hook Failed
+                fail "$(basename "$hook")"
+            ;;
+            2) # Hook Printed Help
+                return 0
+            ;;
+            *) # Unknown result
+                fail "Unknown Result: ($?) : $task/""$(basename "$hook")"
+            ;;
+        esac
+        count=$(( 1 + count ))
+        echo ""
+    done
+
+    header "Finished: $task. ($count) hooks ran."
+    return 0
+}
+
+function list-hooks () {
+    local base="$1"
+    local prefix="$2"
+    local task="$3"
+    shift 3
+    local count=0
+    echo "Active Hooks for $task: "
+    for hook in $(find "$base/$prefix$task" -executable -a -type f | sort -V)
+    do
+        hname=$( basename "$hook" )
+        echo -e "-($count): ${hname}"
+        count=$(( 1 + count ))
+    done
+    exit 0
+}
+
+function run-nth-hook () {
+    local base="$1"
+    local prefix="$2"
+    local nth="$3"
+    local task="$4"
+    shift 4
+    local count=0
+    echo -e "Running hook ($nth) with ($#) args: ${*} "
+
+    for hook in $(find "$base/$prefix$task" -executable -a -type f | sort -V)
+    do
+        hname=$( basename "$hook" )
+        if [[ "$nth" = "$count" ]]; then
+            subhead "Running hook $count: $hname"
+            (
+                POLY_SRC="$POLY_SRC" \
+                    HOOK_NUM="$count" \
+                    "$hook" "$@"
+            )
+            subhead "Skipping remaining hooks"
+            exit 0
+        else
+            subhead "Skipping hook $count: $hname"
+            count=$(( 1 + count ))
+        fi
+    done
+    exit 0
+}
+
 print-help "$@"
-run-task "$POLYGLOT_ROOT/.tasks" "task-" "$@"
+DO_LIST=0
+DO_DRY=0
+NTH_HOOK=""
+TASK_ARGS=()
+TARGET=""
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -l|--list)
+            DO_LIST=1
+            ;;
+        -d|--dry)
+            DO_DRY=1
+            ;;
+        --hook=*)
+            IFS="=" read -ra KEYVAL <<< "$1"
+            NTH_HOOK="${KEYVAL[1]}"
+            ;;
+        *) # Positional
+            TARGET="$1"
+            shift
+            TASK_ARGS=("$@")
+            break
+            ;;
+    esac
+    shift
+done
+
+header "polyglot task"
+
+if [[ "$DO_LIST" = 1 ]]; then
+    list-hooks "$POLYGLOT_ROOT/.tasks" "task-" "$TARGET"
+fi
+
+if [[ -n "${NTH_HOOK:-}" ]]; then
+    run-nth-hook "$POLYGLOT_ROOT/.tasks" "task-" "${NTH_HOOK}" "${TASK_ARGS[@]}"
+else
+    run-task "$POLYGLOT_ROOT/.tasks" "task-" "$DO_DRY" "${TASK_ARGS[@]}"
+fi
diff --git a/polyglot/cmds/polyglot-tool b/polyglot/cmds/polyglot-tool
--- a/polyglot/cmds/polyglot-tool
+++ b/polyglot/cmds/polyglot-tool
@@ -1,11 +1,10 @@
 #!/usr/bin/env bash
 # polyglot-tool -*- mode: sh -*-
-#set -o errexit
+# set -o errexit
 set -o nounset
 set -o pipefail
 
 source "$POLY_SRC/lib/lib-util.bash"
-source "$POLY_SRC/lib/lib-hooks.bash"
 
 function print-help () {
     case "${@: 1}" in
@@ -16,13 +15,106 @@ function print-help () {
            ;;
     esac
     echo -e "
-Run a registered tool cmd.
+usage: polyglot tool [-h] [-l] [toolname subcmd]
+
+Use a registered tool's subcommand.
+
+positional arguments:
+toolname
+subcmd
+
+options:
+-h, --help     :  show this help message and exit
+-l, --list     :  list the available subcmds of the tool
 
 "
     exit 2
 }
 
+function list-subcmds () {
+    local base="$1"
+    local prefix="$2"
+    local tool="$3"
+    shift 3
+    local count=0
+    if [[ -z "$tool" ]]; then
+        fail "No Tool Specified to list subcmds of"
+    elif [[ ! -d "$base/$prefix$tool" ]]; then
+        fail "Tool could not be found: $tool"
+    fi
 
-header "polyglot tool"
+    echo -e "Active Subcommands for $tool: "
+    for subcmd in $(find "$base/$prefix$tool" -executable -a -type f | sort -V)
+    do
+        bname=$( basename "$subcmd" )
+        echo -e "-($count): ${bname}"
+        count=$(( 1 + count ))
+    done
+    exit 0
+}
+
+function run-subcmd () {
+    # run-subcmd {basedir} {subcmd} {args}
+    # task is of the form lang-{sub} or tool-{sub}
+    local base="$1"
+    local prefix="$2"
+    local tool="${3:-}"
+    local target="${4:-}"
+    shift 3
+    local count=0
+    if [[ -z "$target" ]]; then
+        fail "No Applicable tool subcommand specified"
+    fi
+    debug "- Checking for subcommand ${prefix}$tool: $target"
+    if [[ ! -d "$base/$prefix$tool" ]]; then
+        fail "No Applicable Tool Found: ${tool}"
+    fi
+
+    local possible
+    readarray -d '' possible < <(find "$base/${prefix}${tool}" -name "${target}*" -a -executable -print0)
+    if [[ "${#possible[@]}" -lt 0 ]]; then
+        fail "No Possible Subcmds Found"
+    elif [[ "${#possible[@]}" -gt 1 ]]; then
+        fail "Too Many Possible Subcmds Found: ${#possible[@]}"
+    fi
+
+    sub="${possible[0]}"
+    if [[ -x "$sub" ]]; then
+        POLY_SRC="$POLY_SRC" "$sub" "$@"
+        echo "Result: $?"
+        return
+    else
+        echo "not executable"
+    fi
+    return "$NOTHING"
+}
+
 print-help "$@"
-run-subcmd "$POLYGLOT_ROOT/.tasks" "tool-" "$@"
+DO_LIST=0
+TOOL=""
+SUBCMD=""
+TOOL_ARGS=()
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -l|--list)
+            DO_LIST=1
+            ;;
+        *) # Positional
+            if [[ -z "$TOOL" ]]; then
+                TOOL="$1"
+            elif [[ -z "$SUBCMD" ]]; then
+                SUBCMD="$1"
+                shift
+                TOOL_ARGS=("${@}")
+                break
+            fi
+            ;;
+    esac
+    shift
+done
+
+header "polyglot tool: $TOOL.$SUBCMD :(${#TOOL_ARGS[@]}) ${TOOL_ARGS[*]}"
+if [[ "$DO_LIST" = 1 ]]; then
+    list-subcmds "$POLYGLOT_ROOT/.tasks" "tool-" "$TOOL"
+fi
+run-subcmd "$POLYGLOT_ROOT/.tasks" "tool-" "$TOOL" "$SUBCMD" "${TOOL_ARGS[@]}"
